---
title: "S7: Figures and Tables with Captions"
author:
- "Erin Campbell & Elika Bergelson"
output:
    bookdown::pdf_document2:
      number_sections: no
      toc: no
      tables: true
    base_format: rticles::ieee_article
fontsize: 12pt
header-includes: 
  \usepackage{float} \floatplacement{figure}{H} 
  \newcommand{\beginsupplement}{\setcounter{table}{0}  \renewcommand{\thetable}{S\arabic{table}} \setcounter{figure}{0} \renewcommand{\thefigure}{S\arabic{figure}}}
---
To facilitate review, in addition to uploading the elements separately in accordance to JSLHR guidelines, we have combined all tables and figures from the main manuscript and supplemental materials in a single pdf alongside their titles and captions.
\newpage
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load-packages, cache = FALSE, include = FALSE, echo=FALSE}
library(papaja) 
library(tidyverse)
library(knitr)
library(kableExtra)
library(citr)
library(broom)
library(stargazer)
library(glue)
library(magick)
library(cowplot)
library(dotwhisker)
library(car)
library(openxlsx)
library(flextable)
knitr::opts_chunk$set(fig.width=4, fig.height=4, fig.pos="p", comment=F, message=F, hide = T, warning = F, echo = F)
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())
knitr::write_bib(.packages(), file = 'packages.bib')
```

```{r read-in-data, echo = F, results = 'hide', message = F, comment = F, fig.show='hide'}
source("functions_and_df_prep.R")
```

```{r relationships-plot, fig.width=12.5, fig.height=9.5, fig.cap="Co-Occurrence of Child-Level Variables (Chi-Square): Results of chi-square tests between variables. X- and y-axes show the variables compared. Color of the square represents significance of the corresponding chi-square test. For tests that survived Bonferroni correction (p<.0007), effect size (Cramer's V) is given."}
ggplot(chi_sq_all, aes(y=Var2, x=Var1)) +
  geom_tile(aes(fill = sig)) + theme_classic() +
  theme(axis.text.x = element_text(angle = 315, hjust=0.1), 
        axis.text = element_text(size=16),
        legend.text = element_text(size=16)) +
  scale_fill_brewer(palette = "RdPu", direction=-1) +
  geom_text(aes(label=ifelse(sig=='survives Bonferroni correction', round(eff.size,2), '')), 
            size=5) +
  xlab(NULL) + ylab(NULL) +
  ggtitle("Co-Occurrence of Child-Level Variables (Chi-Square)")
```



 
 
```{r vocab-curves-setup}

WG_eng_curves <- ggplot()  + 
  geom_line(data = WG_elssp_eng_gcurve, aes(x=predict_ages, y=scores),colour='black', alpha= .5) + 
  theme_classic() + 
  ylab("CDI Score (WG English)") + 
  xlab("Age in Months") + 
  coord_cartesian(xlim=c(0,40)) + 
  geom_point(data = subset(WG_elssp_eng, !is.na(ProductionCDI)), aes(x= Age_in_months, y= ProductionCDI), shape=1, alpha= .5)+
  theme(legend.position = "none")

WS_eng_curves <- ggplot()  + 
  geom_line(data = WS_elssp_eng_gcurve, aes(x=predict_ages, y=scores),colour='black', alpha= .5) + 
  theme_classic() + 
  ylab("CDI Score (WS English)") + 
  xlab("Age in Months") + 
  coord_cartesian(xlim=c(0,40)) + 
  geom_point(data = subset(WS_elssp_eng, !is.na(ProductionCDI)), aes(x= Age_in_months, y= ProductionCDI), shape=1, alpha= .5) +
  theme(legend.position = "none")

WG_span_curves <- ggplot()  + 
  geom_line(data = WG_elssp_span_gcurve, aes(x=predict_ages, y=scores),colour='black', alpha= .5) + 
  theme_classic() + 
  ylab("CDI Score (WG Spanish)") + 
  xlab("Age in Months") + 
  coord_cartesian(xlim=c(0,40)) + 
  geom_point(data = subset(WG_elssp_span, !is.na(ProductionCDI)), aes(x= Age_in_months, y= ProductionCDI), shape=1, alpha= .5)+
  theme(legend.position = "none")

WS_span_curves <- ggplot()  + 
  geom_line(data = WS_elssp_span_gcurve, aes(x=predict_ages, y=scores),colour='black', alpha= .5) + 
  theme_classic() + 
  ylab("CDI Score (WS Spanish)") + 
  xlab("Age in Months") + 
  coord_cartesian(xlim=c(0,40)) + 
  geom_point(data = subset(WS_elssp_span, !is.na(ProductionCDI)), aes(x= Age_in_months, y= ProductionCDI), shape=1, alpha= .5) +
  theme(legend.position = "none")

plot2_row <- cowplot::plot_grid(WG_eng_curves, WS_eng_curves, WG_span_curves, WS_span_curves)
plot2_title <- ggdraw() + 
  draw_label("Vocabulary Growth Curves by Instrument", fontface = 'bold', x = 0,  hjust = 0) + 
  theme(plot.background = element_rect(fill="white", color = "white"), plot.margin = margin(0, 0, 0, 7))
```

```{r growth-curves, fig.cap="Vocabulary Growth Curves by Instrument: Lines show the growth curves created from WordBank 50th percentile data. Left panels show Words & Gestures; right panels show Words & Sentences. Top row is American English data; bottom row is Mexican Spanish data. Dots represent vocabulary scores of individual DHH children in the sample.", fig.dim = c(6, 6)}
cowplot::plot_grid(plot2_title, plot2_row, ncol=1, rel_heights = c(.1,1))  
```

```{r meets136-timeline, fig.cap="Ages at Clinical Interventions: Age at diagnosis, intervention, amplification, and cochlear implantation across participants. Each dot represents the age that one child received the clinical service; violin width reflects data distribution. Black dots and whiskers show means and standard errors. Not all children received amplification (hearing aids) or implantation (cochlear implants).", fig.dim = c(8, 4)}

gg_SE <- function(x) {
   m <- mean(x)
   ymin <- m-se(x)
   ymax <- m+se(x)
   return(c(y=m,ymin=ymin,ymax=ymax))
}

elssp %>% 
  dplyr::select(VIHI_ID, IdentificationOfHLMonths, AgeStartedServices, AgeAmplification, AgeImplantation) %>%
  rename('Age at Diagnosis'=IdentificationOfHLMonths,
         'Age at Intervention' = AgeStartedServices,
         'Age at Implantation'= AgeImplantation,
         'Age at Amplification' = AgeAmplification) %>%
  pivot_longer(cols = 'Age at Diagnosis':'Age at Implantation', names_to = "event", values_to = "age") %>%
  ggplot(aes(x = event, y = age, fill = event, color = event)) +
  geom_violin(alpha = .4,) +
  geom_jitter(width = .3) + 
  coord_flip() +
  theme_classic(base_size = 16) +
  theme(legend.position = "none") +
  labs(x = '', y ='Age (months)') +
stat_summary(fun.data=gg_SE, color = "black", geom="pointrange")  +
  ggtitle("Ages at Clinical Interventions")
```

```{r delay-violins, fig.cap="Vocabulary Delay and 1-3-6: Estimated vocabulary delay for children who meet 1-3-6 guidelines for diagnosis/intervention (top) and children who do not (bottom). Each dot represents one child in the sample; violin width reflect data distribution. Black dots and whiskers show means and standard error.", fig.dim = c(8, 4),}
t_136 <- t.test(elssp_curves$diff_age_from_expected ~ elssp_curves$Meets136)


ggplot(data=(elssp_curves %>% filter(Meets136!='')), aes(x=Meets136, y=diff_age_from_expected, fill=Meets136, color=Meets136)) +
  geom_violin(alpha=.4)+
  theme_classic(base_size = 16) +
  geom_jitter(width=.15) +
  stat_summary(fun.data=gg_SE, mult=1, 
                 geom="pointrange", color="black") +
  xlab("1-3-6") +
  ylab("Vocabulary Delay (months)") + 
  coord_flip() +
  ggtitle("Vocabulary Delay and 1-3-6")

```

```{r diagnosis-beta-plot}
diagnosis_aic <- lm(formula = IdentificationOfHLMonths ~ HealthIssues + Monolingual_English + Laterality, data = elssp)

diagnosis_beta_plot <- dwplot(diagnosis_aic, by_2sd = FALSE) %>%
  relabel_predictors(HealthIssuesyes = "Health Issues (yes)",
Monolingual_Englishyes = "Language Background (English)",
LateralityUnilateral = "Laterality (Unilateral)") + 
  geom_vline(xintercept=0, linetype = 'dashed') + 
  theme_classic(base_size = 13)+ 
  theme(legend.position="none")
#options(repr.plot.width=8)

```

```{r intervention-beta-plot}
services_aic <- lm(formula = AgeStartedServices ~ HLworse + IsPremature + 
                     IdentificationOfHLMonths + Monolingual_English, data = elssp)


intervention_beta_plot <- dwplot(services_aic, by_2sd = FALSE)  %>%
relabel_predictors(HLworse = "Degree of Hearing Loss",
IsPrematureyes = "Premature (yes)",
IdentificationOfHLMonths = "Age at Diagnosis",
Monolingual_Englishyes = "Language Background (English)") +
  geom_vline(xintercept=0, linetype = 'dashed') + 
  theme_classic(base_size = 13) + 
  theme(legend.position="none")
#options(repr.plot.width=8, repr.plot.height=6) 

```

```{r beta-plots, fig.cap="Beta Weights for Vocabulary, Diagnosis, and Intervention Models: Unstandardized coefficients (measured in months) with 95% confidence intervals for the models selected by AIC for: (A) vocabulary delay, (B) age at diagnosis, (C) age at intervention.", fig.dim=c(8,4)}
AIC_model_delay <- lm(formula = diff_age_from_expected ~ Laterality + Amplification + Age_in_months, data = (elssp_curves %>% filter(PrimaryLanguage != 
    "Hindi" & Meets136!='') %>% droplevels()))

vocab_beta_plot <- dwplot(AIC_model_delay, by_2sd = FALSE) %>%
  relabel_predictors(LateralityUnilateral = "Laterality (Unilateral)",
AmplificationHA= "Amplification (Hearing Aid)",
AmplificationCI= "Amplification (Cochlear Implant)",
Age_in_months = "Age") + 
  theme_classic(base_size = 13) + 
  geom_vline(xintercept = 0, linetype = 'dashed') + 
  theme(legend.position = "none")

plot5_row <- plot_grid(vocab_beta_plot, diagnosis_beta_plot, intervention_beta_plot, labels="AUTO", rows = 3)
plot5_title <- ggdraw() + 
  draw_label("Beta Weights for Vocabulary, Diagnosis, and Intervention Models", fontface = 'bold', x = 0,  hjust = 0) + 
  theme(plot.background = element_rect(fill="white", color = "white"), plot.margin = margin(0, 0, 0, 7))

cowplot::plot_grid(plot5_title, plot5_row, ncol=1, rel_heights = c(.1,1)) 
```


```{r variables-list}
#age
min_age <- round(min(elssp$Age_in_months))
max_age <- round(max(elssp$Age_in_months))
mean_age <- round(mean(elssp$Age_in_months))
sd_age <- round(sd(elssp$Age_in_months))
#age amplification
min_age_amp <- min(elssp$AgeAmplification, na.rm=TRUE)
max_age_amp <- max(elssp$AgeAmplification, na.rm=TRUE)
mean_age_amp <- round(mean(elssp$AgeAmplification, na.rm=TRUE))
sd_age_amp <- round(sd(elssp$AgeAmplification, na.rm=TRUE))
#age diagnosis
min_age_diag <- min(elssp$IdentificationOfHLMonths, na.rm=TRUE)
max_age_diag <- max(elssp$IdentificationOfHLMonths, na.rm=TRUE)
mean_age_diag <- round(mean(elssp$IdentificationOfHLMonths, na.rm=TRUE))
sd_age_diag <- round(sd(elssp$IdentificationOfHLMonths, na.rm=TRUE))
#age implantation
min_age_implant <- min(elssp$AgeImplantation, na.rm=TRUE)
max_age_implant <- max(elssp$AgeImplantation, na.rm=TRUE)
mean_age_implant <- round(mean(elssp$AgeImplantation, na.rm=TRUE))
sd_age_implant <- round(sd(elssp$AgeImplantation, na.rm=TRUE))
#age services
min_age_services <- min(elssp$AgeStartedServices, na.rm=TRUE)
max_age_services <- max(elssp$AgeStartedServices, na.rm=TRUE)
mean_age_services <- round(mean(elssp$AgeStartedServices, na.rm=TRUE))
sd_age_services <- round(sd(elssp$AgeStartedServices, na.rm=TRUE))
#degree
min_degree <- round(min(elssp$HLworse, na.rm=TRUE))
max_degree <- max(elssp$HLworse, na.rm=TRUE)
mean_degree <- round(mean(elssp$HLworse, na.rm=TRUE))
sd_degree <- round(sd(elssp$HLworse, na.rm=TRUE))
#services
min_services <- min(elssp$ServicesReceivedPerMonth, na.rm=TRUE)
max_services <- max(elssp$ServicesReceivedPerMonth, na.rm=TRUE)
mean_services <- round(mean(elssp$ServicesReceivedPerMonth, na.rm=TRUE))
sd_services <- round(sd(elssp$ServicesReceivedPerMonth, na.rm=TRUE))
#WG vocab (production)
min_WG_spoken <- min((elssp%>% filter(CDIversion=="WG"))$ProductionCDI, na.rm=TRUE)
max_WG_spoken <- max((elssp%>% filter(CDIversion=="WG"))$ProductionCDI, na.rm=TRUE)
prod_WG_spoken <- round(mean((elssp %>% filter(CDIversion=="WG"))$ProductionCDI, na.rm = TRUE))
prod_WG_spoken_sd <- round(sd((elssp %>% filter(CDIversion=="WG"))$ProductionCDI, na.rm = TRUE))
#WS vocab
prod_WS_spoken <- round(mean((elssp %>% filter(CDIversion=="WS"))$ProductionCDI, na.rm = TRUE))
prod_WS_spoken_sd <- round(sd((elssp %>% filter(CDIversion=="WS"))$ProductionCDI, na.rm = TRUE))
min_WS_spoken <- min((elssp%>% filter(CDIversion=="WS"))$ProductionCDI, na.rm=TRUE)
max_WS_spoken <- max((elssp%>% filter(CDIversion=="WS"))$ProductionCDI, na.rm=TRUE)

df(tribble(
  ~ Variable,
  ~ Range,
  'Age',
  glue(
    '{min_age}-{max_age} months (mean (SD): {mean_age} ({sd_age}))'
  ),
  'Age at Amplification',
  glue('{min_age_amp}-{max_age_amp} months (mean (SD): {mean_age_amp} ({sd_age_amp}))'
  ),
  'Age at Diagnosis',
  glue('{min_age_diag}-{max_age_diag} months (mean (SD): {mean_age_diag} ({sd_age_diag}))'),
  'Age at Implantation',
  glue('{min_age_implant}-{max_age_implant} months (mean (SD): {mean_age_implant} ({sd_age_implant}))'),
  'Age at Intervention',
  glue(
    '{min_age_services}-{max_age_services} months (mean (SD): {mean_age_services} ({sd_age_services}))'),
  'Amplification',
  glue('Hearing Aid ({nrow(elssp %>% filter(Amplification=="HA"))}) / Cochlear Implant ({nrow(elssp %>% filter(Amplification=="CI"))}) / None ({nrow(elssp %>% filter(Amplification=="none"))})'),
  'Communication',
  glue('Spoken ({nrow(elssp %>% filter(Communication=="spoken"))}) / Total Communication ({nrow(elssp %>% filter(Communication=="total communication"))}) / Cued Speech ({nrow(elssp %>% filter(Communication=="cued speech"))})'),
  'Degree Hearing Loss (worse ear)',
  glue(
    '{min_degree}-{max_degree} dB HL (mean (SD): {mean_degree} ({sd_degree}))'
  ),
  'Developmental Delay',
  glue('Yes ({nrow(elssp %>% filter(DevelopmentalConcerns=="yes"))}) / No ({nrow(elssp %>% filter(DevelopmentalConcerns=="no"))})'),
  'Gender',
  glue('Female ({nrow(elssp %>% filter(Gender=="female"))}) / Male ({nrow(elssp %>% filter(Gender=="male"))})'),
  'Health Issues',
  glue('Yes ({nrow(elssp %>% filter(HealthIssues=="yes"))}) / No ({nrow(elssp %>% filter(HealthIssues=="no"))})'),
  'Language in Home',
  glue('English ({nrow(elssp %>% filter(Monolingual_English=="yes"))}) / Other ({nrow(elssp %>% filter(Monolingual_English=="no"))})'),
  'Laterality',
  glue('Unilateral ({nrow(elssp %>% filter(Laterality=="Unilateral"))}) / Bilateral ({nrow(elssp %>% filter(Laterality=="Bilateral"))})'),
  '1-3-6',
  glue('Yes ({nrow(elssp %>% filter(Meets136=="yes"))}) / No ({nrow(elssp %>% filter(Meets136=="no"))})'),
  'Premature Birth',
  glue('Full-term ({nrow(elssp %>% filter(IsPremature=="yes"))}) / Premature ({nrow(elssp %>% filter(IsPremature=="no"))})'),
  'Services Per Month',
  glue(
    '{min_services}-{max_services} services per month (mean (SD): {mean_services} ({sd_services}))'
  ),
  'Etiology',
  glue('Sensorineural ({nrow(elssp %>% filter(Etiology=="SNHL"))}) / Conductive ({nrow(elssp %>% filter(Etiology=="Conductive"))}) / Mixed ({nrow(elssp %>% filter(Etiology=="Mixed"))})'),
  'Words and Gestures CDI - Words Produced',
  glue(
    '{min_WG_spoken}-{max_WG_spoken} words (mean (SD): {prod_WG_spoken} ({prod_WG_spoken_sd}))'
  ),
  'Words and Sentences CDI - Words Produced',
  glue(
    '{min_WS_spoken}-{max_WS_spoken} words (mean (SD): {prod_WS_spoken} ({prod_WS_spoken_sd}))'
  )
)) %>%
  flextable()
  
  
  
  kable(caption = "Variables List: Detailed information about the variables studied. For categorical variables, levels are described. For continuous variables, range, mean, and standard deviation are provided.") %>%
  # kable_styling(latex_options = c("scale_down")) %>%
  kable_styling(font_size = 6)

# Caption: "Detailed information about the variables studied. For categorical variables, levels are described. For continuous variables, range, mean, and standard deviation are provided."

```

\beginsupplement

```{r lm-stats, include=F}
diagnosis_aic <- lm(formula = IdentificationOfHLMonths ~ HealthIssues + Monolingual_English + Laterality, data = elssp)


services_aic <- lm(formula = AgeStartedServices ~ HLworse + IsPremature + 
                     IdentificationOfHLMonths + Monolingual_English, data = elssp)

```

```{r delay-AIC, include=F}
AIC_model_delay <- lm(formula = diff_age_from_expected ~ Laterality + Amplification + Age_in_months, data = (elssp_curves %>% filter(PrimaryLanguage !=
    "Hindi" & Meets136!='') %>% droplevels()))
summary(AIC_model_delay)
```

```{r comorbid-table}
perc_prem_NICU <- (nrow(comorbid%>%filter(NICU==1&IsPremature==1))/(nrow(elssp %>% filter(IsPremature==1))))*100

tribble(
  ~Condition, ~'Specific Condition',  ~n,
  "Premature", "", n_condition(IsPremature),
  "", "Extremely Premature", n_condition(extremelypremature),
  "", "NICU stay", n_condition(NICU),
  "Health Issues", "", n_condition(HealthIssues),
  "", "Heart", n_condition(heart_issues),
  "", "Lung", n_condition(lung_issues),
  "", "Illness", n_condition(illness),
  "", "Feeding Issues", n_condition(feeding_issues),
  "", "Pregnancy/Birth Complications", n_condition(preg_birth_comp),
  "", "Musculoskeletal", n_condition(mus_skel),
  "", "Cleft Lip/Palate", n_condition(cleft),
  "", "Other", n_condition(health_issues_other),
  "Developmental Concerns", "",  n_condition(DevelopmentalConcerns),
  "", "Down Syndrome", n_condition(downsyndrome),
  "", "Chromosomal Issues", n_condition(otherchromissues),
  "", "Neural Tube Defects", sum(n_condition(encephalocelecyst), n_condition(occipitalencephalocele)),
  "", "Other", sum(n_condition(agenesiscorpuscallosum), n_condition(oculomotorapraxia), n_condition(ventricular_issues), n_condition(corticalvisualimpairment), n_condition(hydrocephalus), n_condition(overalldevconcerns), n_condition(corneliadelange)),
  "Vision Loss", "",  n_condition(VisionLoss),
  "", "Retinopathy of Prematurity",  n_condition(RetinopathyOfPrematurity),
  "", "Nearsightedness",  n_condition(myopia),
  "", "Farsightedness",  n_condition(hyperopia),
  "", "Cortical Visual Impairment",  n_condition(corticalvisualimpairment)) %>%
  kable(caption = "Additional Diagnoses (n = 39): Ns of participants in our sample diagnosed with other conditions. N.B.: Ns do not sum to total because many participants had multiple diagnoses.") %>%
  flextable()
```

```{r supplemental-materials}
elssp %>%
  filter(Amplification != '', Laterality != '') %>%
  dplyr::select(VIHI_ID, AgeImplantation, AgeAmplification, HLbetter, HLworse, Laterality, Amplification) %>%
  group_by(Laterality, Amplification) %>%
  dplyr::summarise('Degree \n(better ear; dB HL)' = round(mean(HLbetter, na.rm = TRUE), 2),
                   'Degree \n(worse ear; dB HL)' = round(mean(HLworse, na.rm = TRUE), 2),
                   'Age of Amplification (months)' = round(mean(AgeAmplification, na.rm = TRUE), 2),
                   'Age of Implantation (months)' = round(mean(AgeImplantation, na.rm = TRUE), 2)) %>%
  kable(caption = "Audiological Characteristics of the Sample: First two columns describe laterality and amplification type (cochlear implant (CI), hearing aid (HA), or none). Mean decibels of hearing loss (HL) in better ear, worse ear, and the mean age (in months) of amplification, and cochlear implantation (when applicable) for each laterality and amplification combination.") %>%
  # kable_styling(latex_options = c("scale_down")) %>%
  kable_styling(font_size = 6)
# Caption:  Audiological Characteristics of the Sample: First two columns describe laterality and amplification type (cochlear implant (CI), hearing aid (HA), or none). Mean decibels of hearing loss (HL) in better ear, worse ear, and the mean age (in months) of amplification, and cochlear implantation (when applicable) for each laterality and amplification combination.

elssp %>%
  filter(PrimaryLanguage != '', Communication != '') %>%
  dplyr::select(VIHI_ID, Communication, PrimaryLanguage) %>%
  group_by(Communication, PrimaryLanguage) %>%
  dplyr::count(name = 'Tally') %>%
  pivot_wider(names_from = PrimaryLanguage, values_from = Tally) %>%
  replace_na(list(English=0, Hindi=0, Spanish=0)) %>%
  mutate(Total = English + Hindi + Spanish) %>%
  kable(caption = "Language and Communication Characteristics of the Sample: Ns of participants by language background and communication method.") %>%
  # kable_styling(latex_options = c("scale_down")) %>%
  flextable()
# Caption: Language and Communication Characteristics of the Sample: Ns of participants by language background and communication method.
```


```{r delay-betas}
AIC_model_delay %>%
  tidy()  %>%
    mutate(term=replace(term, term=="LateralityUnilateral", "Laterality (Unilateral)"),
           term=replace(term, term=="AmplificationCI", "Amplification (Cochlear Implant)"),
           term=replace(term, term=="AmplificationHA", "Amplification (Hearing Aid)"),
           term=replace(term, term=="Age_in_months", "Age (months)")) %>%
  mutate(estimate=round(estimate, 2),
         std.error=round(std.error,2),
         statistic=round(statistic,2),
         p.value=printp(p.value)) %>%
  kable(caption = "Unstandardized beta weights (months of vocabulary delay) for the model of vocabulary delay selected by AIC.") %>%
  # kable_styling(latex_options = c("scale_down")) %>%
  flextable()
  

#Caption:  "Unstandardized beta weights (months of vocabulary delay) for the model of vocabulary delay selected by AIC."
```


```{r diagnosis-betas}
diagnosis_aic %>%
  tidy() %>%
    mutate(term=replace(term, term=="LateralityUnilateral", "Laterality (Unilateral)"),
           term=replace(term, term=="Monolingual_Englishyes", "Language Background (English)"),
           term=replace(term, term=="HealthIssuesyes", "Health Issues (yes)")) %>%
  mutate(estimate=round(estimate, 2),
         std.error=round(std.error,2),
         statistic=round(statistic,2),
         p.value=printp(p.value)) %>%
  kable(caption = "Unstandardized beta weights (months) for the model of diagnosis selected by AIC.") %>%
  # kable_styling(latex_options = c("scale_down")) %>%
  flextable()
# Caption: Unstandardized beta coefficients (months) for the model of age at diagnosis selected by AIC.
```

```{r intervention-betas}

services_aic %>%
  tidy() %>%
    mutate(term=replace(term, term=="HLworse", "Degree of Hearing Loss"),
           term=replace(term, term=="IsPrematureyes", "Premature (yes)"),
           term=replace(term, term=="IdentificationOfHLMonths", "Age at Diagnosis"),
           term=replace(term, term=="Monolingual_Englishyes", "Language Background (English)")) %>%
  mutate(estimate=round(estimate, 2),
         std.error=round(std.error,2),
         statistic=round(statistic,2),
         p.value=printp(p.value)) %>%
  kable(caption = "Unstandardized beta weights (months) for the model of age at intervention selected by AIC.", escape=FALSE) %>%
  # kable_styling(latex_options = c("scale_down")) %>%
  flextable()
#Caption: Unstandardized beta coefficients (months) for the model of age at intervention selected by AIC.
```

